name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        working-directory: handout
        run: uv sync

      - name: Deploy
        working-directory: handout
        run: uv run mkdocs gh-deploy --force